### ISSUE TITLE
template.yml faltando?

### ISSUE THREAD

**Issue by alexhulbert** [filipemansano/alexa-chatgpt#3]
Olá, não consigo executar o `sam deploy` porque está faltando um arquivo template.yml. Você pode enviar o seu? Obrigado!

**Comment by filipemansano** [comment]
> Olá, não consigo executar o `sam deploy` porque está faltando um arquivo template.yml. Você pode enviar o seu? Obrigado!

Oi alex, o arquivo se encontra dentro da pasta [infrastructure](https://github.com/filipemansano/alexa-chatgpt/blob/master/chatgpt/infrastructure/template.yaml), voce pode acionar o `sam deploy` de dentro desse diretorio

**Comment by alexhulbert** [comment]
Muito obrigado pela resposta rápida! Eu estava procurando na árvore de diretórios por "template.yaml" e não "yaml", então não o vi. Tudo está funcionando bem agora!
